backend:
  name: git-gateway
  branch: main
media_folder: "assets/images"
public_folder: "/assets/images"
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "index.html"
        fields:
          - {label: "Body", name: "body", widget: "text"}
